#!/usr/bin/env bash
# Build the bilingual fixture that e2e/bilingual.mjs transcribes.
#
# English, then Mandarin, in one file: the shape of the meeting that exposed
# the bug -- a recording that opens in one language and switches, where
# detecting once at the start gets the rest of it wrong.
#
# Synthesised rather than recorded, and generated by a script rather than
# committed alone, because the alternative is putting a real person's meeting
# in a public repository to test it. macOS's own voices are used, so this needs
# a Mac to regenerate; the .wav it produces is committed so the test itself
# runs anywhere.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/../e2e/fixtures/bilingual.wav"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

say -v Samantha \
  "Right, let's look at the burn rate. Hosting is up eleven percent this quarter, and we agreed to move to the cheaper region." \
  -o "$TMP/en.aiff"

# Meijia is a Mandarin voice. Which script Whisper writes the result in is
# decided by the audio and by the model, not by the voice's locale -- the test
# asserts Han characters, not one script or the other.
say -v Meijia \
  "我们下个星期开会讨论预算的问题。市场部说他们需要更多的时间来准备报告。" \
  -o "$TMP/zh.aiff"

# 16 kHz mono, which is what Whisper wants and what decode.ts resamples to
# anyway. Committing it at the target rate keeps the fixture small.
ffmpeg -y -loglevel error \
  -i "$TMP/en.aiff" -i "$TMP/zh.aiff" \
  -filter_complex "[0:a][1:a]concat=n=2:v=0:a=1[out]" -map "[out]" \
  -ar 16000 -ac 1 "$OUT"

echo "wrote $OUT"
