#!/usr/bin/env python3
"""Generate src/lib/hanzi.ts, the Traditional -> Simplified character table.

Whisper writes Mandarin in whichever script it feels like, and on the same
video it writes both: a stretch transcribed in one pass comes back
Traditional and the same speaker re-read a moment later comes back
Simplified. Asking for Simplified in the interface has to mean something,
and the model has no setting for it, so the conversion happens after.

Only Traditional -> Simplified is generated, and that is deliberate. It is
very nearly one-to-one, so it is safe to apply blindly. The reverse is
one-to-many (Simplified 干 is Traditional 干, 乾 or 幹, and only the
sentence says which), and a table cannot choose correctly.

Source: OpenCC's TSCharacters.txt, Apache-2.0.
  https://github.com/BYVoid/OpenCC

Run:  python3 scripts/make-hanzi.py path/to/TSCharacters.txt
"""
import sys
from pathlib import Path

CJK = [
    (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xF900, 0xFAFF),
    (0x20000, 0x2A6DF), (0x2A700, 0x2EBEF), (0x2F800, 0x2FA1F),
]


def is_han(ch: str) -> bool:
    cp = ord(ch)
    return any(lo <= cp <= hi for lo, hi in CJK)


def main() -> None:
    source = Path(sys.argv[1])
    pairs = []
    seen = set()
    for line in source.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            continue
        trad, values = parts[0], parts[1].split()
        if not values:
            continue
        simp = values[0]
        # Every entry has to be one character to one character, or the
        # substitution would change the length of the text and every cue
        # timing derived from it.
        if len(trad) != 1 or len(simp) != 1:
            continue
        if not is_han(trad) or not is_han(simp):
            continue
        # Basic Multilingual Plane only, and this is not an optimisation.
        # The table is packed as a flat string and read back two characters
        # at a time; JavaScript indexes a string by UTF-16 code unit, so a
        # single character above U+FFFF occupies two of them and shifts
        # every pair after it by one. Shipped once, briefly: it turned 发
        # into 鬆 and 后 into 徑 -- valid characters, entirely wrong words,
        # in someone's subtitles. The CJK Extension blocks do not appear in
        # speech transcripts; correctness here does.
        if ord(trad) > 0xFFFF or ord(simp) > 0xFFFF:
            continue
        if trad == simp or trad in seen:
            continue
        seen.add(trad)
        pairs.append(trad + simp)

    packed = "".join(pairs)
    if len(packed.encode("utf-16-le")) != len(packed) * 2:
        raise SystemExit("a character outside the BMP survived the filter")
    if len(pairs) < 2000:
        raise SystemExit(f"only {len(pairs)} pairs -- that is not the whole table")

    out = Path(__file__).resolve().parent.parent / "src" / "lib" / "hanzi.ts"
    body = packed
    out.write_text(
        "// GENERATED by scripts/make-hanzi.py -- do not edit.\n"
        "//\n"
        "// Traditional -> Simplified, one character to one character, as a\n"
        "// flat string: even positions are Traditional, the odd position\n"
        "// after each is its Simplified form. Flat because a JSON object of\n"
        f"// {len(pairs)} single-character keys costs several times the bytes for\n"
        "// the same data.\n"
        "//\n"
        "// Derived from OpenCC's TSCharacters.txt (Apache-2.0),\n"
        "// https://github.com/BYVoid/OpenCC -- entries that are not a single\n"
        "// Han character on both sides are dropped, so a substitution can\n"
        "// never change the length of a line.\n"
        f"export const TS_PAIRS =\n  \"{body}\";\n",
        encoding="utf-8",
    )
    print(f"{out}: {len(pairs)} pairs, {out.stat().st_size} bytes")


if __name__ == "__main__":
    main()
