// Does a meeting held in two languages come back in two languages?
//
// This is the one check that cannot be faked. Everything else about the
// language path -- the four-second grid, the run merging, where the cut lands
// -- is exercised in `smoke.mjs` against synthetic inputs, in milliseconds.
// None of it proves the thing a user cares about, which is whether Chinese
// speech arrives as Chinese characters.
//
// So this script downloads a real Whisper checkpoint (~80 MB) and runs a real
// bilingual recording through the real pipeline, and it is therefore *not* part
// of `npm run smoke`: a suite that pulls a model on every run is a suite people
// stop running. Run it when the language path changes.
//
//     node e2e/bilingual.mjs [path-to-wav]
//
// The default fixture is generated by `scripts/make-bilingual-fixture.sh`,
// which uses macOS's own speech synthesiser -- English then Mandarin, in one
// file -- so no audio of a real person's meeting is committed to this repo to
// test it.
//
// What it asserts is deliberately coarse: that the Chinese half is *Chinese
// characters* and the English half is Latin script. It says nothing about
// accuracy, because a base checkpoint on synthesised speech has plenty to be
// wrong about and none of it is what broke. What broke was every language being
// decoded as English, and that failure is unmissable at this resolution.

import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = process.argv[2] ?? join(here, "fixtures", "bilingual.wav");

const PORT = 4185;
const BASE = `http://127.0.0.1:${PORT}/`;

const failures = [];
const check = (name, condition, detail = "") => {
  if (condition) console.log(`  ok  ${name}`);
  else {
    failures.push(`${name}${detail ? ` — ${detail}` : ""}`);
    console.log(`FAIL  ${name}${detail ? ` — ${detail}` : ""}`);
  }
};

const audio = readFileSync(fixture).toString("base64");

const server = spawn(
  "npx",
  ["vite", "preview", "--host", "127.0.0.1", "--port", String(PORT), "--strictPort"],
  { cwd: join(here, ".."), stdio: ["ignore", "pipe", "inherit"] },
);
process.on("exit", () => server.kill());
await waitFor(BASE, 20_000);

const browser = await chromium.launch();
const page = await browser.newPage();
page.setDefaultTimeout(600_000);
await page.goto(BASE, { waitUntil: "networkidle" });
await page.waitForFunction(() => Boolean(window.__test?.transcribe));

console.log("  …downloading the model and transcribing (minutes, not seconds)");
const result = await page.evaluate(async (base64) => {
  const { transcribe } = window.__test.transcribe;
  const { decodeToPcm } = window.__test.decode;

  const bytes = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
  const pcm = await decodeToPcm(new Blob([bytes], { type: "audio/wav" }), () => {});

  const out = await transcribe({
    pcm,
    // Base, not tiny.en: an English-only checkpoint has no language tokens at
    // all, which is a different failure from the one under test.
    model: "onnx-community/whisper-base",
    onProgress: () => {},
  });
  return { chunks: out.chunks, languages: out.languages, dominant: out.dominant };
}, audio);

const text = result.chunks.map((chunk) => chunk.text).join(" ");
console.log(`\n  languages: ${result.languages.join(", ")}`);
for (const chunk of result.chunks) {
  console.log(`  ${(chunk.start_ms / 1000).toFixed(1).padStart(5)}s  ${chunk.text}`);
}
console.log("");

const han = /[\u4e00-\u9fff]/;
const latin = /[A-Za-z]{3}/;

// Which chunk is which is decided by what is *in* it, not by where the clock
// says the halves meet. The cut is placed at the pause between the two
// speakers, and that pause is not at a round number of seconds -- an earlier
// version of this file assumed six seconds and failed a working transcript.
const chinese = result.chunks.filter((chunk) => han.test(chunk.text));
const english = result.chunks.filter((chunk) => latin.test(chunk.text) && !han.test(chunk.text));

check(
  "both languages are reported",
  result.languages.includes("zh") && result.languages.includes("en"),
  result.languages.join(","),
);
check("the Chinese is transcribed as Chinese characters", chinese.length > 0);
check("the English is transcribed as English", english.length > 0);
// The bug this file exists for: Chinese decoded as English produced romanised
// syllables or invented English sentences, and no Han characters at all.
check(
  "no stretch of Chinese came back as Latin script",
  chinese.length > 0 && chinese.every((chunk) => !/[A-Za-z]{6}/.test(chunk.text)),
  chinese.map((chunk) => chunk.text).join(" | "),
);
check(
  "the two languages stay in the order they were spoken",
  english.length > 0 && chinese.length > 0 && english[0].start_ms < chinese[0].start_ms,
  `English at ${english[0]?.start_ms}ms, Chinese at ${chinese[0]?.start_ms}ms`,
);
check("nothing came back as decoder debris", !text.includes("\uFFFD"));

await browser.close();
server.kill();

console.log("");
if (failures.length) {
  console.log(`${failures.length} failed:`);
  for (const failure of failures) console.log(`  - ${failure}`);
  process.exit(1);
}
console.log("bilingual: all checks passed");

async function waitFor(url, timeout) {
  const until = Date.now() + timeout;
  for (;;) {
    try {
      if ((await fetch(url)).ok) return;
    } catch {
      // not up yet
    }
    if (Date.now() > until) throw new Error(`${url} never came up`);
    await new Promise((resolve) => setTimeout(resolve, 200));
  }
}
