//! Words that carry no topic.
//!
//! A short list on purpose. A long one starts removing domain words -- "call",
//! "team", "plan", "cost" -- which in a meeting transcript are often exactly
//! the topic. Everything here is either grammatical, or filler that a
//! transcript is full of and a summary should never be.
//!
//! English and the largest Latin-script languages only. Spaceless scripts do
//! not go through this path at all (see `local::term_scores`), and a language
//! with no list here simply keeps its function words -- visible in the topic
//! list, but a milder failure than removing content words by guesswork.

/// Sorted, so the lookup is a binary search rather than a linear scan over a
/// few hundred entries once per token of an hour-long transcript.
const STOPWORDS: &[&str] = &[
    "aber",
    "about",
    "actually",
    "after",
    "again",
    "against",
    "algo",
    "all",
    "alors",
    "already",
    "also",
    "although",
    "always",
    "and",
    "another",
    "any",
    "anything",
    "are",
    "aren",
    "around",
    "auch",
    "aus",
    "avec",
    "back",
    "basically",
    "because",
    "been",
    "before",
    "being",
    "bien",
    "both",
    "but",
    "came",
    "can",
    "cannot",
    "come",
    "comes",
    "coming",
    "could",
    "couldn",
    "dans",
    "das",
    "dass",
    "definitely",
    "dem",
    "den",
    "der",
    "des",
    "did",
    "didn",
    "die",
    "does",
    "doesn",
    "doing",
    "don",
    "done",
    "durch",
    "each",
    "eine",
    "einen",
    "either",
    "else",
    "en",
    "encore",
    "enough",
    "es",
    "est",
    "et",
    "even",
    "ever",
    "every",
    "everything",
    "exactly",
    "from",
    "für",
    "gets",
    "getting",
    "give",
    "going",
    "gonna",
    "got",
    "gotta",
    "guess",
    "had",
    "hadn",
    "has",
    "hasn",
    "have",
    "haven",
    "having",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "however",
    "ich",
    "into",
    "isn",
    "its",
    "itself",
    "just",
    "kind",
    "know",
    "las",
    "les",
    "let",
    "like",
    "look",
    "looking",
    "los",
    "made",
    "mais",
    "make",
    "making",
    "many",
    "maybe",
    "mean",
    "means",
    "might",
    "mine",
    "more",
    "most",
    "much",
    "must",
    "myself",
    "nicht",
    "not",
    "nothing",
    "now",
    "off",
    "okay",
    "once",
    "one",
    "only",
    "onto",
    "other",
    "others",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "para",
    "part",
    "pero",
    "por",
    "pour",
    "pretty",
    "probably",
    "put",
    "que",
    "quite",
    "rather",
    "really",
    "right",
    "said",
    "same",
    "say",
    "saying",
    "says",
    "see",
    "seen",
    "sein",
    "she",
    "should",
    "shouldn",
    "sich",
    "since",
    "some",
    "somebody",
    "something",
    "sort",
    "still",
    "stuff",
    "such",
    "sure",
    "take",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "thing",
    "things",
    "think",
    "this",
    "those",
    "though",
    "through",
    "thus",
    "too",
    "und",
    "under",
    "une",
    "until",
    "use",
    "used",
    "using",
    "very",
    "want",
    "was",
    "wasn",
    "way",
    "well",
    "were",
    "weren",
    "what",
    "whatever",
    "when",
    "where",
    "whether",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "will",
    "with",
    "within",
    "without",
    "won",
    "would",
    "wouldn",
    "yeah",
    "yes",
    "yet",
    "you",
    "your",
    "yours",
    "yourself",
];

pub fn is_stopword(word: &str) -> bool {
    STOPWORDS.binary_search(&word).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The lookup is a binary search, so an unsorted list would silently miss
    /// entries rather than fail loudly.
    #[test]
    fn the_list_is_sorted_and_free_of_duplicates() {
        for pair in STOPWORDS.windows(2) {
            assert!(
                pair[0] < pair[1],
                "{:?} is not before {:?}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn grammar_is_filtered_and_meeting_vocabulary_is_not() {
        for word in ["the", "would", "actually", "yeah", "und", "que"] {
            assert!(is_stopword(word), "{word} should be filtered");
        }
        for word in [
            "budget",
            "hosting",
            "hiring",
            "migration",
            "cost",
            "team",
            "deadline",
        ] {
            assert!(!is_stopword(word), "{word} is a topic, not a stop word");
        }
    }
}
